# Generated by Django 5.1 on 2024-08-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0003_logo_delete_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Логотип'),
        ),
    ]
