# Generated by Django 5.1 on 2024-08-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_options_banner_name_alter_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
